### ISSUE TITLE
选择数量小于设置的最大数量会出错

### ISSUE THREAD

**Issue by bianjiangfront** [ValuesFeng/AndroidPicturePicker#6]
加载速度很快，给个赞

**Comment by ValuesFeng** [comment]
。。。啥情况

**Comment by bianjiangfront** [comment]
放假归来红红火火恍恍惚惚。项目不错，加载速度很快

来自 MEIZU MX

**Comment by bianjiangfront** [comment]
谢大神分享

来自 MEIZU MX

-------- 原始邮件 --------
发件人：ValuesFeng notifications@github.com
时间：周六 10月8日 17:54
收件人：ValuesFeng/AndroidPicturePicker AndroidPicturePicker@noreply.github.com
抄送：bianjiangfront whatwefor@163.com,State change state_change@noreply.github.com
主题：Re: [ValuesFeng/AndroidPicturePicker] 选择数量小于设置的最大数量会出错 (#6)

**Comment by bianjiangfront** [comment]
您好。蟹蟹您的分享。现在选择的图片类型，或者说大小没有限制，出现许多显示不出来的图片。

来自 MEIZU MX

-------- 原始邮件 --------
发件人：ValuesFeng notifications@github.com
时间：周六 10月8日 17:54
收件人：ValuesFeng/AndroidPicturePicker AndroidPicturePicker@noreply.github.com
抄送：bianjiangfront whatwefor@163.com,State change state_change@noreply.github.com
主题：Re: [ValuesFeng/AndroidPicturePicker] 选择数量小于设置的最大数量会出错 (#6)

**Comment by ValuesFeng** [comment]
嗯，确实还有一部分没有完成，目前我暂时搁置下来了。
你要有时间也可以弄弄呀，提个PR给我就行。
